name: Release Please

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v5
        with:
          target-branch: ${{ github.ref_name }}
          config-file: ${{ github.ref_name == 'develop' && '.github/release-please-config-beta.json' || '.github/release-please-config.json' }}
          manifest-file: .release-please-manifest.json
